project:                
  type: website          
  output-dir: docs        #- NO TOCAR: carpeta donde se redirige el output
  
website:
  title: "Big Data en la Euroliga-ACB"
  favicon: logo.jpeg
  # site-url: https://....               #- hay que rellenarlos
  # repo-url: https://....
  # repo-actions: [edit, issue]
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "logo.jpeg"           #---
    #background: "#444444"    #- color de la navbar
    #foreground: "#FF0000"    #- color navigation elements, text and links that appear in the navbar.
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Trabajo individual"   #---
        href: my_trabajo_BigData.qmd   
      - icon: github
        href: https://github.com/vicgau01#--- #---
      - icon: envelope
        url: "mailto:<vicgau@alumni.uv.es>"            #---
  page-footer:
    border: true
    background: "#e66b63"
    left: "© 2022 Victor Gallego"   #----
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/vicgau01    #----  #-----
      - icon: envelope
        url: "mailto:<vicgau>@alumni.uv.es"            #-----
    
format:
  html:
    theme: united           #---
    highlight-style: a11y   #---
    css: my_styles.css   
    page-layout: full
    toc: true
    code-copy: true
    code-overflow: wrap
    code-fold: show
    code-line-numbers: true
    #- {wrap, scroll}
    

# Enable CC licence appendix
license: "CC BY"

lang: es   #- {es, en}


# Default execute options
execute:
  echo: true
  message: false
  warning: false
  eval: true
  
#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica